In [10]:
import numpy as np
from numpy import random

In [ ]:
a = np.zeros(4)
print(f'a is: {a}')

b = np.zeros((4,))
print(f"b is: {b}")

c = random.random_sample(4) * 10
print(np.round(c))

a is: [0. 0. 0. 0.]
b is: [0. 0. 0. 0.]
[1. 8. 5. 5.]


In [27]:
a = np.arange(10.)
print(a)

b = np.random.rand(4)
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.1737485  0.14749601 0.15317872 0.95690518]


In [29]:
a = np.array([2, 3, 4, 1])
b = np.array([2., 3, 4, 1])

print(a, b)
print(a.shape)

[2 3 4 1] [2. 3. 4. 1.]
(4,)


In [33]:
a = np.arange(10)
print(a)

print(a[2].shape, a[2])

[0 1 2 3 4 5 6 7 8 9]
() 2


In [38]:
try:
    print(a[10])
except Exception as e:
    print(e)

index 10 is out of bounds for axis 0 with size 10


In [46]:
a = np.arange(10)
print(a)
print(a[2:7:1])
print(a[2:7:2])
print(a[:3])
print(a[3:])
print(a[:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[0 1 2]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [54]:
a = np.arange(10)
b = [1, 2, 3]
print(a)

# since np.array is a vector it will apply this for all a
c = -a
# this returns an error cause its a normal array
# d = -b

print(c)

print(np.sum(a))

print(np.mean(a))

print(a ** 2)


[0 1 2 3 4 5 6 7 8 9]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
45
4.5
[ 0  1  4  9 16 25 36 49 64 81]


In [59]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])

a1= [1, 2, 3, 4]
a2 = [-1, -2, 3, 4]

c = 0
for i in range(len(a1)):
    c += i + a2[i]
print(c)

print(a + b)


10
[0 0 6 8]


In [ ]:
c = np.array([1, 2])
d = np.array([1, 2, 3])
try:
    print(c + d)
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [62]:
a = np.array([1, 2, 3, 4])

b = 5 * a
print(b)

[ 5 10 15 20]


In [ ]:
# np.dot()

def my_dot (a, b):
    x = 0
    for i in range(a.shape[0]):
        x += a[i] * b[i]
    return x

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

print(my_dot(a, b))

print(np.dot(a, b))

#? why not do this too? (cause its less efficent)
# print(np.sum(a * b))

4
-1
7
16
24
24
24
24


In [95]:
import time

a = np.random.rand(100000)
b = np.random.rand(100000)

tic = time.time()  # start timer
c = np.dot(a, b)
toc = time.time()  # stop timer

print(toc)

tic = time.time()  # start timer
d = my_dot(a, b)
toc = time.time()  # stop timer

print(toc)

1780749367.5874999
100000
0.024182924934947503
0.22510461891602382
0.33737458938124254
0.3707532673269272
0.7766288129839138
1.1794432735323979
1.264780947353335
1.5766578019557511
2.258297037564933
2.862049203459361
3.066567849369077
3.417872721590384
4.028630942704107
4.720861294292133
4.895099044087329
5.579168212561864
5.751680571357576
6.189413894118545
6.497804979190411
7.034996139971366
7.299622415113653
7.492616139395567
7.5839280875037565
7.869852064855085
7.950652878328665
8.393708012212716
9.07091260183001
9.128291510397801
9.468362177864508
9.474925901226383
9.660596501174807
10.086845050664099
10.628684324864835
10.868307604769393
11.042363765040744
11.142587257008783
11.183422655893002
11.408684931529994
11.48050751638115
11.600374215324594
12.051089270017535
12.15812361439247
12.193541646956106
12.846135285180413
12.963641281386218
13.095818311199345
13.552335677626306
13.68127719510641
13.764894015821492
13.815174995924696
13.945513388580263
13.994319926876166
13.996826

In [ ]:
X = np.array([[1], [2], [3], [4]])
w = np.array([5])
c = np.dot(X, w)

print(X.shape[0])
print(w.shape[0])
print(c, c.shape[0])

4
1
[ 5 10 15 20] 4


# Matrices

In [108]:
a = np.zeros((1, 5))
b= np.zeros((4, 1))
c = random.random_sample((1, 1))

print(a, b, c)
print(a.shape[0], b.shape[0], c.shape[0])

[[0. 0. 0. 0. 0.]] [[0.]
 [0.]
 [0.]
 [0.]] [[0.09929381]]
1 4 1


In [ ]:
a = np.arange(6)
print(a)
# -1 automatically calculates columns
b = a.reshape(-1, 2)
print(b)

print(b[0, 1])

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
1
[3]


In [137]:
a = np.arange(20)
b = a.reshape(-1, 5)

print(b[2][1:4:1])
print(b[:][1:4:1])
print(b[2][:])
print(b[:][:])

[11 12 13]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
