In [121]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [122]:
X = np.array(
    [
        [1, 4],
        [2, 5],
        [2, 3],
        [3, 4],
        [4, 5],
        [4, 3],
        [5, 6],
        [5, 4],
        [6, 5],
        [7, 6],
        [7, 4],
        [8, 7],
    ],
    dtype=np.float32,
)

Y = np.array([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1], dtype=np.float32)

In [123]:
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(X)
Xn = norm_l(X)

print(Xn, Y)
print(Xn.shape, Y.shape)

tf.Tensor(
[[-1.6348476  -0.56568533]
 [-1.1677483   0.28284284]
 [-1.1677483  -1.4142134 ]
 [-0.700649   -0.56568533]
 [-0.23354967  0.28284284]
 [-0.23354967 -1.4142134 ]
 [ 0.23354967  1.131371  ]
 [ 0.23354967 -0.56568533]
 [ 0.700649    0.28284284]
 [ 1.1677483   1.131371  ]
 [ 1.1677483  -0.56568533]
 [ 1.6348476   1.9798992 ]], shape=(12, 2), dtype=float32) [0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1.]
(12, 2) (12,)


In [124]:
Xt = np.tile(Xn, (1000, 1))
Yt = np.tile(Y, (1000))

print(Xt.shape, Yt.shape)


(12000, 2) (12000,)


In [125]:
print(Xt.shape)
print(Yt.shape)

(12000, 2)
(12000,)


In [126]:
tf.random.set_seed(1234)
model = Sequential(
    [
        tf.keras.Input(shape=(2,)), # Number of Features
        Dense(3, activation="sigmoid", name="L1"),
        Dense(1, activation="sigmoid", name="L2"),
    ]
)

In [127]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ (None, 3)              │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L2 (Dense)                      │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

In [128]:
w1, b1 = model.layers[0].get_weights() # method 1 to get layer
w2, b2 = model.get_layer('L2').get_weights() # method to get layer

print(w1.shape, b1.shape)
print(w1, "\n", b1)

print(w2.shape, b2.shape)

(2, 3) (3,)
[[-0.24228686  0.97737384  0.04826033]
 [-0.38215888 -0.01716018 -0.85868657]] 
 [0. 0. 0.]
(3, 1) (1,)


In [129]:
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
    )

model.fit(
    Xt, Yt,
    epochs=10,
)

Epoch 1/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2105
Epoch 2/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0257
Epoch 3/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0094
Epoch 4/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0049
Epoch 5/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0030
Epoch 6/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0020
Epoch 7/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0014
Epoch 8/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0010
Epoch 9/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8652e-04
Epoch 10/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 6.0434e-04


In [138]:
print(f"layer 1, Old Weight: {w1}, \n old Bias: {b1}")
print(f"\n layer2, Old Weight: {w2}, old Bias: {b2}")

w_trained1, b_trained1 = model.layers[0].get_weights()
w_trained2, b_trained2 = model.layers[1].get_weights()

print(f"\n \n layer 1, Trained Weight: {w_trained1}, \n trained Bias: {b_trained1}")
print(f"\n layer2, Trained Weight: {w_trained2}, trained Bias: {b_trained2}")

layer 1, Old Weight: [[-0.24228686  0.97737384  0.04826033]
 [-0.38215888 -0.01716018 -0.85868657]], 
 old Bias: [0. 0. 0.]

 layer2, Old Weight: [[-0.49930203]
 [ 0.65779746]
 [-0.12498379]], old Bias: [0.]

 
 layer 1, Trained Weight: [[-4.927812   5.1808577 -5.802108 ]
 [-2.8823526  2.8290854 -3.446872 ]], 
 trained Bias: [-2.6776547  2.736929  -3.1667223]

 layer2, Trained Weight: [[-5.487461 ]
 [ 5.7366586]
 [-5.346497 ]], trained Bias: [2.3911512]


In [186]:

x_test = np.array([[2, 1], [3, 8]])

x_test_norm = norm_l(x_test)

print(x_test_norm)

tf.Tensor(
[[-1.1677483 -3.1112697]
 [-0.700649   2.8284273]], shape=(2, 2), dtype=float32)


In [188]:
y_preds = model.predict(x_test_norm)

yhat = (y_preds >= 0.5).astype(int)

print(yhat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
[[0]
 [1]]
