# Data types in Numpy

### Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )


In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [4]:
arr = np.array(["apple", "banana", "cherry"])

print(arr.dtype)

<U6


In [5]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# gets stored in 8-bit data so 4*8 = 32
arr = np.array([1, 2, 3, 4], dtype="i4")

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# raises Error
arr = np.array(["a", "2", "3"], dtype="i")

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newArr = arr.astype('i')

print(newArr)
print(newArr.dtype)

[1 2 3]
int32


In [14]:
arr = np.array([1.1, 2.1, 3.1])

newArr = arr.astype(int)

print(newArr)
print(newArr.dtype)

[1 2 3]
int64


In [15]:
arr = np.array([1, 2, 0, 3, 0])

newArr = arr.astype(bool)

print(newArr)
print(newArr.dtype)

[ True  True False  True False]
bool
