In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4])

arrCopied = arr.copy()

arr[0] = 100

print(arr ,'\n', arrCopied)

[100   2   3   4] 
 [1 2 3 4]


In [ ]:
arr = np.array([1, 2, 3, 4])

arrCopied = arr.view()

arr[0] = 100

print(arr, "\n", arrCopied)

[100   2   3   4] 
 [100   2   3   4]


In [ ]:
arr = np.array([1, 2, 3, 4])

arrViewed = arr.view()

arrViewed[0] = 100

print(arr, "\n", arrCopied)

[100   2   3   4] 
 [100   2   3   4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

arrCopied = arr.copy()
arrViewed= arr.view()

#? If owns data returns None otherwise points to its data
print(arrCopied.base)
print(arrViewed.base) 

None
[1 2 3 4 5]
