In [2]:
import numpy as np

# 1-D Array

In [3]:
arr = np.array([1 ,2 ,3])

for i in arr:
    print(i)

1
2
3


# 2-D Array

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    print(i)

[1 2 3]
[4 5 6]


## Iterating Through 1-D dimentions Elements

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Iterates horrizentally
for x in arr:
    # Iterates Vertically
    for y in x:
        print(y)

1
2
3
4
5
6


# 3-D Aarrays

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# nditer: Tool for iterating

In [8]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# The Hard Way

# for x in arr:
#     for y in x:
#         for z in y:
#             print(z)

# Easy Way
for i in np.nditer(arr): # n-dimentional iterator
    print(i)

1
2
3
4
5
6
7
8


In [9]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


 # Enumerated Iteration Using ndenumerate()

In [11]:

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for index, x in np.ndenumerate(arr):
    print(index, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
