In [1]:
import numpy as np

# Joining to Arrays Together using concatenate

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arrJoined = np.concatenate((arr1, arr2))

print(arrJoined)

[1 2 3 4 5 6]


In [18]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arrJoined = np.concatenate((arr1, arr2), axis=1)

print(arrJoined)

[[1 2 5 6]
 [3 4 7 8]]


In [28]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr_stacked = np.stack((arr1, arr2), axis=0)

print(arr_stacked)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [29]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
