In [1]:
import numpy as np


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

# returns Indexes of where '4' is appeared
where_in_arr = np.where(arr == 4)

print(where_in_arr)

(array([3, 5, 6]),)


In [10]:
arr = np.array([10, 14, 93, 41, 8, 7])

index_odd1 = np.where(~(arr % 2 == 0))
index_odd2 = np.where((arr % 2 == 1))

print(index_odd1)
print(index_odd2)

(array([2, 3, 5]),)
(array([2, 3, 5]),)


# Search Sorted

In [ ]:
arr = np.array([6, 7, 8, 9])

arr_search_sorted = np.searchsorted(arr, 7)

# Returns the index of where to insert 7 to maintain order
print(arr_search_sorted)

1


In [ ]:
arr = np.array([6, 7, 8, 9])

# index from right side
arr_search_sorted = np.searchsorted(arr, 7, side='right')

print(arr_search_sorted)

2


In [ ]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [18]:
arr = np.array([6, 7, 8, 9])

x = np.where(arr > 7)
print (x)

(array([2, 3]),)
