In [2]:
import numpy as np

In [ ]:
arr = np.array([3, 2, 0, 1])

#NOTE: Creates a Copy
arr_sorted = np.sort(arr)

print(arr_sorted)

[0 1 2 3]


In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])
 
arr_sorted = np.sort(arr)

print(arr_sorted)

['apple' 'banana' 'cherry']


In [5]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

#NOTE: Sorts Both
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
