# Generating Random Numbers

In [ ]:
from numpy import random


79


In [20]:

x = random.randint(100)

print(x)

17


# Random Float

In [ ]:
x = random.rand() 

print(x)

0.5780144281747052


# Random Arrays

In [ ]:
x = random.randint(100, size=5)

print(x)

[10 99 86 46 14]


In [ ]:
x = random.randint(100, size=(5, 3)) # Returns a 5x3 matrix

print(x)

[[79 80 69]
 [84 30 90]
 [37 38 15]
 [76 56 63]
 [92 46 70]]


In [ ]:
x = random.rand(5)

print(x)

[0.10238143 0.35227574 0.12398017 0.29584327 0.11363398]


In [ ]:
x = random.rand(3, 5)

print(x)

[[0.7102391  0.66380766 0.21641488 0.28251163 0.3185899 ]
 [0.2452449  0.7521426  0.9777365  0.79874855 0.52772511]
 [0.10559398 0.83693756 0.98719364 0.69783515 0.2966591 ]]


In [ ]:
#NOTE: size is the number of choices
x = random.choice([1, 2, 3, 4], size=2)

print(x)

[4 2]


In [64]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[5 3 3 9 9]
 [5 7 5 3 9]
 [7 3 7 9 7]]
