In [1]:
import numpy as np
from numpy import random

# What is the Probablity of a number to occure

In [5]:
x = random.choice([2, 3, 1, 5], p=[0.1, 0.3, 0.6, 0.0], size=100)

print(x)

[3 1 3 1 1 3 3 2 1 1 1 1 1 2 1 1 1 1 1 3 1 3 3 1 1 1 3 1 1 1 1 2 3 3 2 1 1
 2 1 1 1 2 3 1 1 3 1 3 1 3 1 1 1 1 3 1 1 2 3 2 3 1 1 1 3 1 3 1 1 3 1 2 2 1
 1 1 1 1 2 1 3 1 1 1 3 3 3 3 1 1 1 3 3 1 3 3 2 1 3 1]


In [15]:
x = random.choice([2, 3, 1, 5], p=[0.1, 0.3, 0.6, 0.0], size=(3,5))

print(x)

[[1 1 3 3 1]
 [3 2 3 1 1]
 [1 1 2 3 1]]
