In [3]:
from numpy import random 
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Changes the Original Array
random.shuffle(arr)

print(arr)

[3 4 5 2 1]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Leaves the Original Array unchanged
print(random.permutation(arr))

[4 3 1 5 2]
None


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Leaves the Original Array unchanged
print(random.permutation(arr))

[4 3 1 5 2]
None
